[package]
name = "pageinfo-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pageinfo-rs"
path = "src/main.rs"

[lib]
name = "pageinfo_rs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
dom-content-extraction = "0.3"
futures = "0.3"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spider_chrome = "2.37"
toml = "0.8"
spider_fingerprint = "2.37"
thiserror = "2.0.12"
tokio = { version = "1.46", features = ["full"] }
url = "2.5"
wreq = "5.2"
wreq-util = "2.2"
