[package]
name = "pageinfo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.2"
dom-content-extraction = "0.2.7"
regex = "1.7.3"
reqwest = "0.11.16"
tokio = { version = "1.27.0", features = ["full"] }
