[package]
name = "pageinfo-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
dom-content-extraction = "0.3"
futures = "0.3.31"
futures-util = "0.3"
reqwest = "0.12"
serde_json = "1.0.140"
spider_chrome = "2.37"
spider_fingerprint = "2.37.119"
tokio = { version = "1.46", features = ["full"] }
